In [19]:
import numpy as np, sys, random
def toseconds(x):
    return 0 #placeholder
timeseries=np.zeros([365,4])
timeseries[:,2]=np.loadtxt('NICS_daily.np')
ts_SP=np.loadtxt('ts_AR_SP.np')
ix1=ts_SP[:,0].astype(int)
timeseries[ix1,0]=ts_SP[:,1]
ts_FoR=np.loadtxt('ts_AR_FoR.np')
ix2=ts_FoR[:,0].astype(int)
timeseries[ix2,1]=ts_FoR[:,1]
ts_AR=np.loadtxt('ts_AR.np')
ix3=ts_AR[:,0].astype(int)
timeseries[ix3,3]=ts_AR[:,1]
timeseries[:,0]=np.nan_to_num(timeseries[:,0]/timeseries[:,3])
timeseries[:,1]=np.nan_to_num(timeseries[:,1]/timeseries[:,3])
mn=170
mx=250
timeseries=timeseries[mn:mx,:]
def te(x,y,y1):
    x=x.astype(np.int32)
    y=y.astype(np.int32)
    y1=y1.astype(np.int32)
    p_joint=np.zeros(8)
    p_num=np.zeros(8)
    p_denom=np.zeros(8)
    s=0
    for i0 in range(2):
        for i1 in range(2):
            for j0 in range(2):
                n_y1yx=0
                n_y1y=0
                N_joint=0
                N_num=0
                N_denom=0
                for n in range(len(x)):
                    n_y1yx+=1 if (x[n]==j0 and y[n]==i0 and y1[n]==i1) else 0
                    n_y1y+=1 if y[n]==i0 and y1[n]==i1 else 0
                    N_joint+=1
                    N_num+=1 if x[n]==j0 and y[n]==i0 else 0
                    N_denom+=1 if y[n]==i0 else 0
                p_joint[s]=n_y1yx/N_joint if N_joint>0 else 0
                p_num[s]=n_y1yx/N_num if N_num>0 else 0
                p_denom[s]=n_y1y/N_denom if N_denom>0 else 0
                s+=1   
        
    TE=0
    for s in range(8):
        if p_joint[s]>0:
            TE+=p_joint[s]*np.log(p_num[s]/p_denom[s])
    return TE

i=1
def quantize(x):
    return 1*(x>np.median(x))
Y1=quantize(timeseries[1:,2])
Y0=quantize(timeseries[:-1,2])
X0=quantize(timeseries[:-1,i])
def shuffled(x):
    return quantize(np.random.permutation(x))

t=te(X0,Y0,Y1)
print(t)
Ntest=10000
Stest=np.zeros(Ntest)
for T in range(Ntest):
    Stest[T]=te(shuffled(timeseries[:-1,i]),Y0,Y1)
print((Stest)[int(Ntest*0.95)], Stest.min(),Stest.max())
print(1-len(np.where(Stest<t)[0])/Ntest)

<ipython-input-19-a61d1ff0f6b7>:15: RuntimeWarning: invalid value encountered in true_divide
  timeseries[:,0]=np.nan_to_num(timeseries[:,0]/timeseries[:,3])
<ipython-input-19-a61d1ff0f6b7>:16: RuntimeWarning: invalid value encountered in true_divide
  timeseries[:,1]=np.nan_to_num(timeseries[:,1]/timeseries[:,3])

0.010354748845205708
0.023263902223448006 2.123230681572749e-05 0.08496558148390182
0.2773

In [115]:
import pandas as pd
pd.read_csv('results_multi2.csv')

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Tweet,SurveyID,Pro-Gun Regulation,Anti-Gun Regulation,Fear of Regulation,Self-Defense,Pro-Regulation Fear of Regulation,Pro-Regulation Self-Defense,Anti-Regulation Fear of Regulation,Anti-Regulation Self-Defense,Political Ideology Scale,Precent Tests Passed,Age,Seconds,State,Username,Longitude,Latitude,DbID
0,007fuego you are really dumb af if you think g...,14760,False,True,True,False,False,False,True,False,0,0.25,21.0,18637266.0,michigan,BQarana,-83.0302,42.5803,938921
1,007fuego you are really dumb af if you think g...,14760,False,True,True,False,False,False,True,False,0,0.25,21.0,15191647.0,arizona,BridgeASU,-111.9400,33.4255,225499
2,007fuego you are really dumb af if you think g...,14760,False,True,True,False,False,False,True,False,0,0.25,21.0,15281409.0,texas,ShellzXoX,-99.5121,31.8160,222253
3,007fuego you are really dumb af if you think g...,14760,False,True,True,False,False,False,True,False,0,0.25,21.0,15349411.0,ohio,DiegoMachete,-82.3513,38.5584,214755
4,007fuego you are really dumb af if you think g...,14760,False,True,True,False,False,False,True,False,0,0.25,21.0,15381030.0,mississippi,callmechelss,-90.2381,31.6143,209591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3456065,zvezda73 aristeia hollywoodholmes davidhogg111...,35107,False,False,False,False,False,False,False,False,3,0.00,NaN,15744487.0,oregon,CoolBreeze018,-120.7370,43.9793,349883
3456066,zvezda73 aristeia hollywoodholmes davidhogg111...,35107,False,False,False,False,False,False,False,False,3,0.00,NaN,16656263.0,alabama,filmguy205,-86.5133,33.9907,646290
3456067,zvezda73 aristeia hollywoodholmes davidhogg111...,35107,False,False,False,False,False,False,False,False,3,0.00,NaN,15651594.0,arkansas,GregCampNC,-92.4479,35.2049,318151
3456068,zvezda73 aristeia hollywoodholmes davidhogg111...,35122,True,False,False,True,False,True,False,False,5,0.50,35.0,16419429.0,massachusetts,DaysWithDave,-71.0583,42.3603,590092
3456069,zvezda73 aristeia hollywoodholmes davidhogg111...,35122,True,False,False,True,False,True,False,False,5,0.50,35.0,15744487.0,oregon,CoolBreeze018,-120.7370,43.9793,349883